name: Generate Pacman Game from Contribution Grid

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Game
        uses: Platane/generate-pacman-game-from-github-contribution-grid@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: README.md 
